# Generated by Django 2.2.2 on 2019-06-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('roll_number', models.IntegerField()),
                ('gender', models.CharField(choices=[('f', 'female'), ('m', 'male')], max_length=1)),
            ],
        ),
    ]
